//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGL.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FFD_ITEM_ACCOUNT_HIS
    {
        public string aply_no { get; set; }
        public string exec_action { get; set; }
        public string item { get; set; }
        public string item_kind { get; set; }
        public string fund_ac_corp_no { get; set; }
        public string item_account { get; set; }
        public string item_desc { get; set; }
        public string item_remark { get; set; }
        public string item_transfer { get; set; }
        public System.DateTime item_effective_date { get; set; }
        public Nullable<System.DateTime> item_expiration_date { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string appr_stat { get; set; }
    }
}
