//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGL.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGL_PAY_MAIN_HIS
    {
        public string pk_id { get; set; }
        public string pay_class { get; set; }
        public string memo_o { get; set; }
        public string memo_n { get; set; }
        public string item_yn_o { get; set; }
        public string item_yn_n { get; set; }
        public string year_yn_o { get; set; }
        public string year_yn_n { get; set; }
        public string prem_yn_o { get; set; }
        public string prem_yn_n { get; set; }
        public string unit_yn_o { get; set; }
        public string unit_yn_n { get; set; }
        public string recp_yn_o { get; set; }
        public string recp_yn_n { get; set; }
        public string cont_yn_o { get; set; }
        public string cont_yn_n { get; set; }
        public string corp_yn_o { get; set; }
        public string corp_yn_n { get; set; }
        public string exec_action { get; set; }
        public string apply_status { get; set; }
        public string apply_id { get; set; }
        public Nullable<System.DateTime> apply_datetime { get; set; }
        public string appr_id { get; set; }
        public Nullable<System.DateTime> appr_datetime { get; set; }
    }
}
