//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGL.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGL_ITEM_SMPNUM_HIS
    {
        public string aply_no { get; set; }
        public string item { get; set; }
        public string product_type { get; set; }
        public string fu_mk { get; set; }
        public string item_con { get; set; }
        public string disc_part_feat { get; set; }
        public string smp_num { get; set; }
        public string acct_type { get; set; }
        public string data_type { get; set; }
        public string flag { get; set; }
    }
}
