//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGL.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGL_ITEM_INFO
    {
        public string item { get; set; }
        public string product_type { get; set; }
        public string fu_mk { get; set; }
        public string item_con { get; set; }
        public string disc_part_feat { get; set; }
        public string prod_no_ver { get; set; }
        public string prod_no { get; set; }
        public string sys_type { get; set; }
        public string item_main_type { get; set; }
        public string invest_type { get; set; }
        public string ins_term { get; set; }
        public string busi_type { get; set; }
        public string com_type { get; set; }
        public string ext_schedul_type { get; set; }
        public string pakind_dmop_type { get; set; }
        public string lodprm_type { get; set; }
        public string item_name { get; set; }
        public string item_acct { get; set; }
        public string separat_acct { get; set; }
        public string coi_acct { get; set; }
        public Nullable<System.DateTime> effect_date { get; set; }
        public string eff_mk { get; set; }
        public string appr_mk { get; set; }
        public string prod_upd_id { get; set; }
        public Nullable<System.DateTime> prod_upd_dt { get; set; }
        public string prod_appr_id { get; set; }
        public Nullable<System.DateTime> prod_appr_dt { get; set; }
        public string invest_upd_id { get; set; }
        public Nullable<System.DateTime> invest_upd_dt { get; set; }
        public string invest_appr_id { get; set; }
        public Nullable<System.DateTime> invest_appr_dt { get; set; }
        public string acct_upd_id { get; set; }
        public Nullable<System.DateTime> acct_upd_dt { get; set; }
        public string acct_appr_id { get; set; }
        public Nullable<System.DateTime> acct_appr_dt { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> create_dt { get; set; }
        public string flag { get; set; }
        public string health_mgr_type { get; set; }
        public string coi_type { get; set; }
        public string item_name_shrt { get; set; }
    }
}
