//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGL.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGL_SMP_NUM_RULE
    {
        public decimal seq { get; set; }
        public string smp_rule_type { get; set; }
        public string smp_rule_desc { get; set; }
        public string fu_mk { get; set; }
        public string smp_rule_product_type { get; set; }
        public string prod_no_4 { get; set; }
        public string prod_no_5 { get; set; }
        public string prod_no_6 { get; set; }
        public string prod_no_7 { get; set; }
        public string prod_no_8 { get; set; }
        public string item_acct_5 { get; set; }
        public string item_acct_6 { get; set; }
        public string item_acct_7 { get; set; }
        public string item_acct_8_10 { get; set; }
        public Nullable<decimal> takenum_interval { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    }
}
