//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGL.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGL_PAY_SUB_HIS
    {
        public string pk_id { get; set; }
        public string main_pk_id { get; set; }
        public string pay_class { get; set; }
        public string prem_kind_o { get; set; }
        public string prem_kind_n { get; set; }
        public string cont_type_o { get; set; }
        public string cont_type_n { get; set; }
        public string prod_type_o { get; set; }
        public string prod_type_n { get; set; }
        public string corp_no_o { get; set; }
        public string corp_no_n { get; set; }
        public string actnum_yn_o { get; set; }
        public string actnum_yn_n { get; set; }
        public string acct_code_o { get; set; }
        public string acct_code_n { get; set; }
        public string acct_codef_o { get; set; }
        public string acct_codef_n { get; set; }
        public string acct_coder_o { get; set; }
        public string acct_coder_n { get; set; }
        public string exec_action { get; set; }
    }
}
