//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGL.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGL_ITEM_CODE_TRAN_HIS
    {
        public string aply_no { get; set; }
        public string product_no { get; set; }
        public string exec_action { get; set; }
        public string tran_a { get; set; }
        public string tran_b { get; set; }
        public string tran_c { get; set; }
        public string tran_d { get; set; }
        public string tran_e { get; set; }
        public string tran_f { get; set; }
        public string tran_g { get; set; }
        public string tran_h { get; set; }
        public string tran_i { get; set; }
        public string tran_j { get; set; }
        public string tran_k { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string appr_stat { get; set; }
    }
}
