//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGL.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGL_SMP_NUM_SEQ
    {
        public decimal seq_item_acct_5_6 { get; set; }
        public decimal seq_item_acct_7 { get; set; }
        public decimal seq_item_acct_8_10 { get; set; }
        public decimal next_seq { get; set; }
        public string item { get; set; }
        public string item_acct { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    }
}
