//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGL.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XAC279350738548
    {
        public string APLY_NO { get; set; }
        public string FLAG { get; set; }
        public string CORP_NO { get; set; }
        public string VOUCHER_NO { get; set; }
        public Nullable<System.DateTime> VOUCHER_DATE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> ENTRY_TIME { get; set; }
        public string A_SYS_TYPE { get; set; }
        public string A_ACTNUM_LASTSIX { get; set; }
        public string A_INSUR_POLICY_ITEM { get; set; }
        public string A_INSUR_POLICY_OBJECT_NO { get; set; }
        public string A_INSUR_POLICY_OBJECT_NAME { get; set; }
        public string A_INSUR_POLICY_MAJOR_CATEGORIES { get; set; }
        public string A_INSUR_POLICY_SUBDIVISIONS { get; set; }
        public string A_INSUR_POLICY_PERSON_GROUP { get; set; }
        public string A_CONTRACT_TYPE { get; set; }
        public string A_INSUR_POLICY_TRADITION { get; set; }
        public string A_INSUR_POLICY_BUSINESS_OBJECT { get; set; }
        public string A_INSUR_POLICY_MAIN_OR_RIDER { get; set; }
        public string A_INSUR_POLICY_OBJECT_TYPE_1 { get; set; }
        public string A_INSUR_POLICY_OBJECT_TYPE_2 { get; set; }
        public string A_INSUR_POLICY_MAIN_INSUR_TYPE { get; set; }
        public string A_INSUR_POLICY_DANGER_TYPE { get; set; }
        public string A_INSUR_POLICY_IS_PAR { get; set; }
        public string DETAIL_REMARK { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string FIELD_CHA_1 { get; set; }
        public string FIELD_CHA_2 { get; set; }
        public string FIELD_CHA_3 { get; set; }
        public string FIELD_CHA_4 { get; set; }
        public string FIELD_CHA_5 { get; set; }
        public string A_INSUR_POLICY_INDEX { get; set; }
        public string A_INSUR_POLICY_STRATEGY_OBJECT { get; set; }
        public string A_INSUR_POLICY_RAPID_REPORT_CATEGORY_1 { get; set; }
        public string A_INVESTMENT_INSURANCE_CONTRACT { get; set; }
        public string A_YM1_CODE { get; set; }
        public string A_EXAMINE_SPECIAL_PAYMENT { get; set; }
    }
}
