//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_AUTH_MGR
    {
        public string auth_unit { get; set; }
        public string mgr_unit { get; set; }
        public string is_disabled { get; set; }
        public string memo { get; set; }
        public string data_status { get; set; }
        public string create_uid { get; set; }
        public Nullable<System.DateTime> create_dt { get; set; }
        public string last_update_uid { get; set; }
        public Nullable<System.DateTime> last_update_dt { get; set; }
        public string appr_uid { get; set; }
        public Nullable<System.DateTime> appr_dt { get; set; }
        public string freeze_uid { get; set; }
        public Nullable<System.DateTime> freeze_dt { get; set; }
    }
}
