//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFGLEntities : DbContext
    {
        public dbFGLEntities()
            : base("name=dbFGLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PIA_EXEC_TYPE> PIA_EXEC_TYPE { get; set; }
        public virtual DbSet<PIA_LOG_MAIN> PIA_LOG_MAIN { get; set; }
        public virtual DbSet<PIA_TRACK_TYPE> PIA_TRACK_TYPE { get; set; }
        public virtual DbSet<PIA_TRN_HIST> PIA_TRN_HIST { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<CODE_USER_HIS> CODE_USER_HIS { get; set; }
        public virtual DbSet<CODE_USER_ROLE> CODE_USER_ROLE { get; set; }
        public virtual DbSet<CODE_USER_ROLE_HIS> CODE_USER_ROLE_HIS { get; set; }
        public virtual DbSet<SYS_SEQ> SYS_SEQ { get; set; }
        public virtual DbSet<CODE_ROLE_FUNC> CODE_ROLE_FUNC { get; set; }
        public virtual DbSet<CODE_ROLE_FUNC_HIS> CODE_ROLE_FUNC_HIS { get; set; }
        public virtual DbSet<CODE_SYS_INFO> CODE_SYS_INFO { get; set; }
        public virtual DbSet<CODE_FUNC> CODE_FUNC { get; set; }
        public virtual DbSet<CODE_ROLE_HIS> CODE_ROLE_HIS { get; set; }
        public virtual DbSet<CODE_ROLE> CODE_ROLE { get; set; }
        public virtual DbSet<SYS_PARA> SYS_PARA { get; set; }
        public virtual DbSet<CODE_USER> CODE_USER { get; set; }
        public virtual DbSet<SSO_APLY_REC> SSO_APLY_REC { get; set; }
        public virtual DbSet<SYS_CODE> SYS_CODE { get; set; }
        public virtual DbSet<CODE_AUTH_MGR> CODE_AUTH_MGR { get; set; }
    }
}
