//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIA_TRN_HIST
    {
        public int HIST_ID { get; set; }
        public long TRACKSEQ_START { get; set; }
        public long TRACKSEQ_END { get; set; }
        public System.DateTime EXEC_DATE { get; set; }
        public System.TimeSpan EXEC_TIME { get; set; }
    }
}
