//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PARA
    {
        public string SYS_CD { get; set; }
        public string PARA_ID { get; set; }
        public string PARA_VALUE { get; set; }
        public string REMARK { get; set; }
        public string RESERVE1 { get; set; }
        public string RESERVE2 { get; set; }
        public string RESERVE3 { get; set; }
        public string GRP_ID { get; set; }
    }
}
