//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OA_EMP
    {
        public string EMP_NAME { get; set; }
        public string EMP_NAME_E { get; set; }
        public string FUN_CD { get; set; }
        public string EMP_NO { get; set; }
        public string ID_NO { get; set; }
        public string USR_ID { get; set; }
        public string EmailAddress { get; set; }
        public string HO_TEL { get; set; }
        public string ext { get; set; }
        public string fax_fr { get; set; }
        public string fax_no { get; set; }
        public string mobile { get; set; }
        public string bbcall { get; set; }
        public string WORK_LOC { get; set; }
        public string DPT_CD { get; set; }
        public string MGR_EMPNO { get; set; }
        public string JobStatus { get; set; }
        public string HO_ADD { get; set; }
    }
}
