//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OA_DEPT
    {
        public string DPT_NAME { get; set; }
        public string DPT_CD { get; set; }
        public string GRP_CD { get; set; }
        public string UP_DPT_CD { get; set; }
        public string Dpt_type { get; set; }
        public string DPT_HEAD { get; set; }
    }
}
