//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferWorkingKey.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_MAIL_NOTIFY
    {
        public string GROUP_CODE { get; set; }
        public string RECEIVER_EMPNO { get; set; }
        public string EMP_TYPE { get; set; }
        public string IS_NOTIFY_MGR { get; set; }
        public string MEMO { get; set; }
        public string IS_NOTIFY_DEPT_MGR { get; set; }
        public string RESERVE1 { get; set; }
        public string RESERVE2 { get; set; }
        public string RESERVE3 { get; set; }
        public string DATA_STATUS { get; set; }
        public string UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string APPR_ID { get; set; }
        public Nullable<System.DateTime> APPR_DT { get; set; }
    }
}
