//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRTXmlMonitor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_XML_LOG_DETAIL
    {
        public string fast_no { get; set; }
        public string operation_status { get; set; }
        public System.DateTime create_date { get; set; }
        public System.TimeSpan create_time_hms { get; set; }
    
        public virtual FRT_XML_LOG FRT_XML_LOG { get; set; }
    }
}
