//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFGLEntities : DbContext
    {
        public dbFGLEntities()
            : base("name=dbFGLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PIA_EXEC_TYPE> PIA_EXEC_TYPE { get; set; }
        public virtual DbSet<PIA_LOG_MAIN> PIA_LOG_MAIN { get; set; }
        public virtual DbSet<PIA_TRACK_TYPE> PIA_TRACK_TYPE { get; set; }
        public virtual DbSet<PIA_TRN_HIST> PIA_TRN_HIST { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<CODE_ROLE_HIS> CODE_ROLE_HIS { get; set; }
        public virtual DbSet<CODE_USER_HIS> CODE_USER_HIS { get; set; }
        public virtual DbSet<CODE_USER_ROLE_HIS> CODE_USER_ROLE_HIS { get; set; }
        public virtual DbSet<SYS_SEQ> SYS_SEQ { get; set; }
        public virtual DbSet<CODE_SYS_INFO> CODE_SYS_INFO { get; set; }
        public virtual DbSet<FRT_MAIL_LOG> FRT_MAIL_LOG { get; set; }
        public virtual DbSet<SYS_PARA> SYS_PARA { get; set; }
        public virtual DbSet<SYS_PARA_HIS> SYS_PARA_HIS { get; set; }
        public virtual DbSet<CODE_USER> CODE_USER { get; set; }
        public virtual DbSet<FRT_XML_522657> FRT_XML_522657 { get; set; }
        public virtual DbSet<FRT_XML_R_622685> FRT_XML_R_622685 { get; set; }
        public virtual DbSet<FRT_XML_R_622821> FRT_XML_R_622821 { get; set; }
        public virtual DbSet<FRT_XML_R_eACH> FRT_XML_R_eACH { get; set; }
        public virtual DbSet<FRT_XML_T_622821> FRT_XML_T_622821 { get; set; }
        public virtual DbSet<FRT_XML_T_622685> FRT_XML_T_622685 { get; set; }
        public virtual DbSet<FRT_XML_T_eACH> FRT_XML_T_eACH { get; set; }
        public virtual DbSet<FRT_CODE_HIS> FRT_CODE_HIS { get; set; }
        public virtual DbSet<SYS_CODE> SYS_CODE { get; set; }
        public virtual DbSet<CODE_FUNC> CODE_FUNC { get; set; }
        public virtual DbSet<CODE_ROLE> CODE_ROLE { get; set; }
        public virtual DbSet<CODE_ROLE_FUNC> CODE_ROLE_FUNC { get; set; }
        public virtual DbSet<CODE_USER_ROLE> CODE_USER_ROLE { get; set; }
        public virtual DbSet<FRT_MAIL_NOTIFY> FRT_MAIL_NOTIFY { get; set; }
        public virtual DbSet<FRT_MAIL_NOTIFY_HIS> FRT_MAIL_NOTIFY_HIS { get; set; }
        public virtual DbSet<FRT_FBO> FRT_FBO { get; set; }
        public virtual DbSet<FRT_SCHEDULE_JOB> FRT_SCHEDULE_JOB { get; set; }
        public virtual DbSet<FRT_WORD> FRT_WORD { get; set; }
        public virtual DbSet<FRT_WORD_HIS> FRT_WORD_HIS { get; set; }
        public virtual DbSet<FRT_XML_LOG> FRT_XML_LOG { get; set; }
        public virtual DbSet<FRT_XML_LOG_DETAIL> FRT_XML_LOG_DETAIL { get; set; }
        public virtual DbSet<FRT_XML_R_622823> FRT_XML_R_622823 { get; set; }
        public virtual DbSet<FRT_XML_T_622685_NEW> FRT_XML_T_622685_NEW { get; set; }
        public virtual DbSet<FRT_XML_R_622685_NEW> FRT_XML_R_622685_NEW { get; set; }
        public virtual DbSet<FRT_XML_T_622823> FRT_XML_T_622823 { get; set; }
        public virtual DbSet<FRT_RVMN_HIS> FRT_RVMN_HIS { get; set; }
        public virtual DbSet<FRT_CROSS_SYSTEM_CHECK> FRT_CROSS_SYSTEM_CHECK { get; set; }
        public virtual DbSet<FRT_CROSS_SYSTEM_CHECK_DETAIL> FRT_CROSS_SYSTEM_CHECK_DETAIL { get; set; }
        public virtual DbSet<FRT_CROSS_SYSTEM_CHECK_DETAIL_HIS> FRT_CROSS_SYSTEM_CHECK_DETAIL_HIS { get; set; }
        public virtual DbSet<FRT_CROSS_SYSTEM_CHECK_HIS> FRT_CROSS_SYSTEM_CHECK_HIS { get; set; }
        public virtual DbSet<FRT_CROSS_SYSTEM_EXCEPT_ACCT_NO> FRT_CROSS_SYSTEM_EXCEPT_ACCT_NO { get; set; }
        public virtual DbSet<FRT_CROSS_SYSTEM_EXCEPT_ACCT_NO_HIS> FRT_CROSS_SYSTEM_EXCEPT_ACCT_NO_HIS { get; set; }
    }
}
