//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_WORD
    {
        public string frt_word_id { get; set; }
        public string frt_sys_type { get; set; }
        public string frt_srce_from { get; set; }
        public string frt_srce_kind { get; set; }
        public string frt_memo_apx { get; set; }
        public string frt_achcode { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string data_status { get; set; }
        public string appr_id { get; set; }
        public Nullable<System.DateTime> approve_datetime { get; set; }
    }
}
