//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_CROSS_SYSTEM_CHECK
    {
        public string check_id { get; set; }
        public string type { get; set; }
        public string kind { get; set; }
        public string frequency { get; set; }
        public int frequency_value { get; set; }
        public System.TimeSpan scheduler_time { get; set; }
        public string start_date_type { get; set; }
        public string start_date_value { get; set; }
        public string mail_group { get; set; }
        public string data_status { get; set; }
        public string create_id { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string update_id { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string appr_id { get; set; }
        public System.DateTime appr_datetime { get; set; }
        public string run_flag { get; set; }
        public string mail_key { get; set; }
    }
}
