//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_XML_R_eACH
    {
        public int ID { get; set; }
        public string HEADER { get; set; }
        public string REQUESTID { get; set; }
        public string SEQNO { get; set; }
        public string ACHSTAN { get; set; }
        public string TXNCODE { get; set; }
        public string ACHCODE { get; set; }
        public string TXNAMT { get; set; }
        public string TXNINBANK { get; set; }
        public string TXNOUTBANK { get; set; }
        public string TRANSFERINACTNO { get; set; }
        public string TRANSFEROUTACTNO { get; set; }
        public string INIDNO { get; set; }
        public string OUTIDNO { get; set; }
        public string USERNO { get; set; }
        public string MERCHANTID { get; set; }
        public string ORDERNO { get; set; }
        public string TERMID { get; set; }
        public string MEMO { get; set; }
        public string CHARGEFEE { get; set; }
        public string ACHBIZDATE { get; set; }
        public string O360TXNSEQNO { get; set; }
        public string STLFLAG { get; set; }
        public string ERROR_CODE { get; set; }
        public string EMSGID { get; set; }
        public string EMSGTXT { get; set; }
        public string SQL_STS { get; set; }
        public Nullable<System.DateTime> CRT_TIME { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string FAST_NO { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    }
}
