//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_CROSS_SYSTEM_EXCEPT_ACCT_NO_HIS
    {
        public string his_pk_id { get; set; }
        public string bank_acct_no { get; set; }
        public string pk_id { get; set; }
        public string exec_action { get; set; }
        public string apply_status { get; set; }
        public string apply_id { get; set; }
        public System.DateTime apply_datetime { get; set; }
        public string appr_id { get; set; }
        public Nullable<System.DateTime> appr_datetime { get; set; }
    }
}
