//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_CODE_HIS
    {
        public string APPLY_NO { get; set; }
        public string GROUP_ID { get; set; }
        public decimal TEXT_LEN { get; set; }
        public string REF_NO { get; set; }
        public string TEXT { get; set; }
        public string SRCE_FROM { get; set; }
        public string USE_MARK { get; set; }
        public string UPDATE_ID { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public string APPR_STAT { get; set; }
        public string APPR_ID { get; set; }
        public Nullable<System.DateTime> APPROVE_DATETIME { get; set; }
        public string REF_NO_N { get; set; }
        public string STATUS { get; set; }
    }
}
