//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_XML_R_622821
    {
        public int ID { get; set; }
        public string HEADER { get; set; }
        public string ACT_DATE { get; set; }
        public string PRE_REQSRL { get; set; }
        public string SETL_ID { get; set; }
        public string MSG_TYPE { get; set; }
        public string TX_AMT { get; set; }
        public string FEE_AMT { get; set; }
        public string SIGN_ACT { get; set; }
        public string ACT_BAL { get; set; }
        public string SIGN_AVAL { get; set; }
        public string AVAL_BAL { get; set; }
        public string PRE_REQDATE { get; set; }
        public string EMSGID { get; set; }
        public string EMSGTXT { get; set; }
        public string RC_CODE { get; set; }
        public string SQL_STS { get; set; }
        public Nullable<System.DateTime> CRT_TIME { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string FAST_NO { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    }
}
