//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_RVMN_HIS
    {
        public string aply_no { get; set; }
        public string corp_no { get; set; }
        public string vhr_no1 { get; set; }
        public string pro_no { get; set; }
        public string paid_id { get; set; }
        public string currency { get; set; }
        public string fail_code { get; set; }
        public string seqn { get; set; }
        public string fail_code_o { get; set; }
        public string seqn_o { get; set; }
        public string appr_stat { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string appr_id { get; set; }
        public Nullable<System.DateTime> approve_datetime { get; set; }
    }
}
