//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_XML_522657
    {
        public string FAST_NO { get; set; }
        public string T_HEADER { get; set; }
        public string T_IRMT_DATE { get; set; }
        public string IRMT_SRLNO { get; set; }
        public string T_BRH_COD { get; set; }
        public string R_HEADER { get; set; }
        public string R_IRMT_DATE { get; set; }
        public string IRMT_TIME { get; set; }
        public string RMT_AMT { get; set; }
        public string RMT_TYPE { get; set; }
        public string RMT_BNK { get; set; }
        public string RMT_BNK_NAME { get; set; }
        public string RCV_BNK { get; set; }
        public string RCV_BNK_NAME { get; set; }
        public string RCV_ACT_NO { get; set; }
        public string RCV_CUST_NAME { get; set; }
        public string EC_RCV_ACT_NO { get; set; }
        public string EC_CUST_NAME { get; set; }
        public string RCV_NAME { get; set; }
        public string EC_RCV_NAME { get; set; }
        public string RMT_NAME { get; set; }
        public string RMT_APX { get; set; }
        public string IRMT_STS { get; set; }
        public string PRS_RSLT { get; set; }
        public string PRS_DATE { get; set; }
        public string TLXSNO { get; set; }
        public string BTBSNO { get; set; }
        public string RETURN_DATE { get; set; }
        public string PRS_SRLNO { get; set; }
        public string ORG_BTBSNO { get; set; }
        public string REJ_RSN_TXT { get; set; }
        public string EMP_ID { get; set; }
        public string PRS_SUP_ID { get; set; }
        public string R_BRH_COD { get; set; }
        public string ORG_RMT_SRLNO { get; set; }
        public string ORG_RMT_DATE { get; set; }
        public string ERROR_COD { get; set; }
        public Nullable<System.DateTime> CRT_TIME { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
    }
}
