//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_XML_T_622821
    {
        public int ID { get; set; }
        public string HEADER { get; set; }
        public string TRAN_ID { get; set; }
        public string TX_RMK { get; set; }
        public string ACT_DATE { get; set; }
        public string PRE_REQDATE { get; set; }
        public string PRE_REQSRL { get; set; }
        public string PAY_IDNO { get; set; }
        public string NAME_COD { get; set; }
        public string SETL_ID { get; set; }
        public string PAY_BANK { get; set; }
        public string ACNO_OUT { get; set; }
        public string CERT_BKID { get; set; }
        public string CERT_NO { get; set; }
        public string RCV_BANK { get; set; }
        public string RCV_ACNO { get; set; }
        public string TX_AMT { get; set; }
        public string FEE_COD { get; set; }
        public string REF_NO { get; set; }
        public string PAY_NAME { get; set; }
        public string RCV_NAME { get; set; }
        public string APX { get; set; }
        public string AG_BKID { get; set; }
        public string MAC { get; set; }
        public string SYNC { get; set; }
        public string ICV { get; set; }
        public string SQL_STS { get; set; }
        public Nullable<System.DateTime> CRT_TIME { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string FAST_NO { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    }
}
