//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRQxml.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_XML_T_622685
    {
        public string HEADER { get; set; }
        public string ACT_DATE { get; set; }
        public string BRH_TYPE_01 { get; set; }
        public string ITEM_NO { get; set; }
        public string SQL_STS { get; set; }
        public Nullable<System.DateTime> CRT_TIME { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string EXEC_TYPE { get; set; }
        public string CRT_UID { get; set; }
    }
}
