//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRTXml.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbGLEntities : DbContext
    {
        public dbGLEntities()
            : base("name=dbGLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FRT_MAC> FRT_MAC { get; set; }
        public virtual DbSet<SYS_PARA> SYS_PARA { get; set; }
        public virtual DbSet<FRT_XML_R_622821> FRT_XML_R_622821 { get; set; }
        public virtual DbSet<FRT_XML_R_eACH> FRT_XML_R_eACH { get; set; }
        public virtual DbSet<FRT_XML_T_eACH> FRT_XML_T_eACH { get; set; }
        public virtual DbSet<FRT_WorkingKey> FRT_WorkingKey { get; set; }
        public virtual DbSet<CODE_ROLE> CODE_ROLE { get; set; }
        public virtual DbSet<CODE_USER> CODE_USER { get; set; }
        public virtual DbSet<CODE_USER_ROLE> CODE_USER_ROLE { get; set; }
        public virtual DbSet<FRT_MAIL_LOG> FRT_MAIL_LOG { get; set; }
        public virtual DbSet<FRT_MAIL_NOTIFY> FRT_MAIL_NOTIFY { get; set; }
        public virtual DbSet<SYS_SEQ> SYS_SEQ { get; set; }
        public virtual DbSet<FRT_XML_T_622821> FRT_XML_T_622821 { get; set; }
        public virtual DbSet<FRT_WORD> FRT_WORD { get; set; }
        public virtual DbSet<FRT_XML_LOG> FRT_XML_LOG { get; set; }
        public virtual DbSet<FRT_XML_LOG_DETAIL> FRT_XML_LOG_DETAIL { get; set; }
        public virtual DbSet<FRT_XML_R_622823> FRT_XML_R_622823 { get; set; }
        public virtual DbSet<FRT_XML_T_622823> FRT_XML_T_622823 { get; set; }
    }
}
