//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRT_FTP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCLIFEDD
    {
        public string TX_DATE { get; set; }
        public string TX_TIME { get; set; }
        public string CK_NO { get; set; }
        public string MEMO { get; set; }
        public string WT_AMT { get; set; }
        public string DEP_AMT { get; set; }
        public string BAL_AMT { get; set; }
        public string TX_BRH { get; set; }
        public string RMK { get; set; }
        public string BNK_COD { get; set; }
        public string ACCT_NO { get; set; }
        public string ACNO_SA { get; set; }
        public string CUR { get; set; }
        public string BNK_COD_C { get; set; }
        public int IdNo { get; set; }
    }
}
