//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRQxml.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_XML_R_622685_NEW
    {
        public int ID { get; set; }
        public string HEADER { get; set; }
        public string BufferData { get; set; }
        public string HeadUUID { get; set; }
        public string FunCode { get; set; }
        public string Status { get; set; }
        public string ucaErrorCod { get; set; }
        public string ucaIRMTSrlNo { get; set; }
        public string ucaOrgRmtSrlNo { get; set; }
        public string NewRmtSrlNo { get; set; }
        public string TxnTime { get; set; }
        public string TelSeq { get; set; }
        public string NextKey { get; set; }
        public string SQL_STS { get; set; }
        public System.DateTime CRT_TIME { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string HERRID { get; set; }
        public string EMSGTXT { get; set; }
        public string FAST_NO { get; set; }
        public Nullable<System.DateTime> ActDate { get; set; }
    }
}
