//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRQxml.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRT_XML_R_622685
    {
        public string HEADER { get; set; }
        public string ETARRY { get; set; }
        public string SETL_ID { get; set; }
        public string RMT_TYPE { get; set; }
        public string STATUS { get; set; }
        public string ERROR_COD { get; set; }
        public string ORG_RMT_SRLNO { get; set; }
        public string NEW_RMT_SRLNO { get; set; }
        public string IRMT_SRLNO { get; set; }
        public string SQL_STS { get; set; }
        public System.DateTime CRT_TIME { get; set; }
        public Nullable<System.DateTime> UPD_TIME { get; set; }
        public string HERRID { get; set; }
        public string EMSGTXT { get; set; }
        public string FAST_NO { get; set; }
    }
}
