//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fubon.Resource {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fubon.Resource.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 發生例外狀況，請重整頁面後再嘗試，或通知服務人員。 的當地語系化字串。
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最大長度為{0}個字 的當地語系化字串。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最小長度為{0}個字 的當地語系化字串。
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MQMachine值為空白。 的當地語系化字串。
        /// </summary>
        public static string MqError1 {
            get {
                return ResourceManager.GetString("MqError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AS400Machine值為空白。 的當地語系化字串。
        /// </summary>
        public static string MqError2 {
            get {
                return ResourceManager.GetString("MqError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MessageID：定義在AS400上面所呼叫AS400程式名稱的對照碼，不可以空白。 的當地語系化字串。
        /// </summary>
        public static string MqError3 {
            get {
                return ResourceManager.GetString("MqError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SendBuffer：傳送內容，不可以空白。 的當地語系化字串。
        /// </summary>
        public static string MqError4 {
            get {
                return ResourceManager.GetString("MqError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 找不到MQ電文元件。 的當地語系化字串。
        /// </summary>
        public static string MqErrorN1 {
            get {
                return ResourceManager.GetString("MqErrorN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MQ送出失敗。 的當地語系化字串。
        /// </summary>
        public static string MqErrorN2 {
            get {
                return ResourceManager.GetString("MqErrorN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MQ送出後沒有結果。 的當地語系化字串。
        /// </summary>
        public static string MqErrorN3 {
            get {
                return ResourceManager.GetString("MqErrorN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MQ送出後沒有Key。 的當地語系化字串。
        /// </summary>
        public static string MqErrorN4 {
            get {
                return ResourceManager.GetString("MqErrorN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MQ回傳的一個Key，不可以空白。 的當地語系化字串。
        /// </summary>
        public static string MqErrorN5 {
            get {
                return ResourceManager.GetString("MqErrorN5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MQRecvReq送出失敗。 的當地語系化字串。
        /// </summary>
        public static string MqErrorN6 {
            get {
                return ResourceManager.GetString("MqErrorN6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取回傳值時發生異常錯誤。 的當地語系化字串。
        /// </summary>
        public static string MqErrorN7 {
            get {
                return ResourceManager.GetString("MqErrorN7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作逾時，請重新登入或聯絡系統負責人，謝謝！ 的當地語系化字串。
        /// </summary>
        public static string SysErrorContent {
            get {
                return ResourceManager.GetString("SysErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發生錯誤 的當地語系化字串。
        /// </summary>
        public static string SysErrorTitle {
            get {
                return ResourceManager.GetString("SysErrorTitle", resourceCulture);
            }
        }
    }
}
