//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APLY_REC_HIS
    {
        public string APLY_NO { get; set; }
        public System.DateTime PROC_DT { get; set; }
        public string APLY_STATUS { get; set; }
        public string PROC_UID { get; set; }
    }
}
