//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLANK_NOTE_APLY
    {
        public string APLY_NO { get; set; }
        public string ITEM_ID { get; set; }
        public string ISSUING_BANK { get; set; }
        public string CHECK_TYPE { get; set; }
        public string CHECK_NO_TRACK { get; set; }
        public string CHECK_NO_B { get; set; }
        public string CHECK_NO_E { get; set; }
        public string ITEM_BLANK_NOTE_ITEM_ID { get; set; }
        public string ITEM_BLANK_NOTE_FINAL_ITEM_ID { get; set; }
    }
}
