//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_FUNC
    {
        public string SYS_CD { get; set; }
        public string FUNC_ID { get; set; }
        public string PARENT_FUNC_ID { get; set; }
        public string FUNC_NAME { get; set; }
        public int FUNC_LEVEL { get; set; }
        public string FUNC_MEMO { get; set; }
        public string FUNC_URL { get; set; }
        public int FUNC_ORDER { get; set; }
        public string IS_DISABLED { get; set; }
        public string CREATE_UID { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string LAST_UPDATE_UID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
    }
}
