//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_CHG_APLY
    {
        public string APLY_NO { get; set; }
        public string ITEM_ID { get; set; }
        public string APPR_STATUS { get; set; }
        public string CHG_AUTH_UNIT { get; set; }
        public string CREATE_UID { get; set; }
        public Nullable<System.DateTime> CREATE_Date { get; set; }
        public Nullable<System.TimeSpan> CREATE_Time { get; set; }
        public string APPR_UID { get; set; }
        public Nullable<System.DateTime> APPR_Date { get; set; }
        public Nullable<System.TimeSpan> APPR_Time { get; set; }
    }
}
