//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_BOOK
    {
        public string ITEM_ID { get; set; }
        public int GROUP_NO { get; set; }
        public string COL { get; set; }
        public string COL_NAME { get; set; }
        public string COL_VALUE { get; set; }
    }
}
