//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_STOCK
    {
        public string ITEM_ID { get; set; }
        public string INVENTORY_STATUS { get; set; }
        public int GROUP_NO { get; set; }
        public int TREA_BATCH_NO { get; set; }
        public string STOCK_TYPE { get; set; }
        public string STOCK_NO_PREAMBLE { get; set; }
        public string STOCK_NO_B { get; set; }
        public string STOCK_NO_E { get; set; }
        public Nullable<int> STOCK_CNT { get; set; }
        public Nullable<decimal> AMOUNT_PER_SHARE { get; set; }
        public Nullable<decimal> SINGLE_NUMBER_OF_SHARES { get; set; }
        public Nullable<decimal> DENOMINATION { get; set; }
        public Nullable<decimal> NUMBER_OF_SHARES { get; set; }
        public string MEMO { get; set; }
        public string APLY_DEPT { get; set; }
        public string APLY_SECT { get; set; }
        public string APLY_UID { get; set; }
        public string CHARGE_DEPT { get; set; }
        public string CHARGE_SECT { get; set; }
        public Nullable<System.DateTime> PUT_DATE { get; set; }
        public Nullable<System.DateTime> GET_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public string STOCK_TYPE_AFT { get; set; }
        public string STOCK_NO_PREAMBLE_AFT { get; set; }
        public string STOCK_NO_B_AFT { get; set; }
        public string STOCK_NO_E_AFT { get; set; }
        public Nullable<int> STOCK_CNT_AFT { get; set; }
        public Nullable<decimal> AMOUNT_PER_SHARE_AFT { get; set; }
        public Nullable<decimal> SINGLE_NUMBER_OF_SHARES_AFT { get; set; }
        public Nullable<decimal> DENOMINATION_AFT { get; set; }
        public Nullable<decimal> NUMBER_OF_SHARES_AFT { get; set; }
        public string MEMO_AFT { get; set; }
        public string CHARGE_DEPT_AFT { get; set; }
        public string CHARGE_SECT_AFT { get; set; }
        public string STOCK_TYPE_ACCESS { get; set; }
        public string STOCK_NO_PREAMBLE_ACCESS { get; set; }
        public string STOCK_NO_B_ACCESS { get; set; }
        public string STOCK_NO_E_ACCESS { get; set; }
        public Nullable<int> STOCK_CNT_ACCESS { get; set; }
        public Nullable<decimal> DENOMINATION_ACCESS { get; set; }
        public Nullable<decimal> NUMBER_OF_SHARES_ACCESS { get; set; }
        public string MEMO_ACCESS { get; set; }
        public Nullable<decimal> AMOUNT_PER_SHARE_ACCESS { get; set; }
        public Nullable<decimal> SINGLE_NUMBER_OF_SHARES_ACCESS { get; set; }
    }
}
