//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_DEP_ORDER_D
    {
        public string ITEM_ID { get; set; }
        public int DATA_SEQ { get; set; }
        public string DEP_NO_PREAMBLE { get; set; }
        public string DEP_NO_B { get; set; }
        public string DEP_NO_E { get; set; }
        public string DEP_NO_TAIL { get; set; }
        public int DEP_CNT { get; set; }
        public decimal DENOMINATION { get; set; }
        public decimal SUBTOTAL_DENOMINATION { get; set; }
        public string DEP_NO_PREAMBLE_AFT { get; set; }
        public string DEP_NO_B_AFT { get; set; }
        public string DEP_NO_E_AFT { get; set; }
        public string DEP_NO_TAIL_AFT { get; set; }
        public Nullable<int> DEP_CNT_AFT { get; set; }
        public Nullable<decimal> DENOMINATION_AFT { get; set; }
        public Nullable<decimal> SUBTOTAL_DENOMINATION_AFT { get; set; }
        public string DEP_NO_PREAMBLE_ACCESS { get; set; }
        public string DEP_NO_B_ACCESS { get; set; }
        public string DEP_NO_E_ACCESS { get; set; }
        public string DEP_NO_TAIL_ACCESS { get; set; }
        public Nullable<int> DEP_CNT_ACCESS { get; set; }
        public Nullable<decimal> DENOMINATION_ACCESS { get; set; }
        public Nullable<decimal> SUBTOTAL_DENOMINATION_ACCESS { get; set; }
    }
}
