//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_DEP_ORDER_M
    {
        public string ITEM_ID { get; set; }
        public string INVENTORY_STATUS { get; set; }
        public string CURRENCY { get; set; }
        public string TRAD_PARTNERS { get; set; }
        public System.DateTime COMMIT_DATE { get; set; }
        public System.DateTime EXPIRY_DATE { get; set; }
        public string INTEREST_RATE_TYPE { get; set; }
        public decimal INTEREST_RATE { get; set; }
        public string DEP_TYPE { get; set; }
        public decimal TOTAL_DENOMINATION { get; set; }
        public string DEP_SET_QUALITY { get; set; }
        public string AUTO_TRANS { get; set; }
        public Nullable<System.DateTime> TRANS_EXPIRY_DATE { get; set; }
        public Nullable<int> TRANS_TMS { get; set; }
        public string MEMO { get; set; }
        public string APLY_DEPT { get; set; }
        public string APLY_SECT { get; set; }
        public string APLY_UID { get; set; }
        public string CHARGE_DEPT { get; set; }
        public string CHARGE_SECT { get; set; }
        public Nullable<System.DateTime> PUT_DATE { get; set; }
        public Nullable<System.DateTime> GET_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public string CURRENCY_AFT { get; set; }
        public string TRAD_PARTNERS_AFT { get; set; }
        public Nullable<System.DateTime> COMMIT_DATE_AFT { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE_AFT { get; set; }
        public string INTEREST_RATE_TYPE_AFT { get; set; }
        public Nullable<decimal> INTEREST_RATE_AFT { get; set; }
        public string DEP_TYPE_AFT { get; set; }
        public Nullable<decimal> TOTAL_DENOMINATION_AFT { get; set; }
        public string DEP_SET_QUALITY_AFT { get; set; }
        public string AUTO_TRANS_AFT { get; set; }
        public Nullable<System.DateTime> TRANS_EXPIRY_DATE_AFT { get; set; }
        public Nullable<int> TRANS_TMS_AFT { get; set; }
        public string MEMO_AFT { get; set; }
        public string CHARGE_DEPT_AFT { get; set; }
        public string CHARGE_SECT_AFT { get; set; }
        public string GET_MSG { get; set; }
        public string CURRENCY_ACCESS { get; set; }
        public string TRAD_PARTNERS_ACCESS { get; set; }
        public Nullable<System.DateTime> COMMIT_DATE_ACCESS { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE_ACCESS { get; set; }
        public string INTEREST_RATE_TYPE_ACCESS { get; set; }
        public Nullable<decimal> INTEREST_RATE_ACCESS { get; set; }
        public string DEP_TYPE_ACCESS { get; set; }
        public Nullable<decimal> TOTAL_DENOMINATION_ACCESS { get; set; }
        public string DEP_SET_QUALITY_ACCESS { get; set; }
        public string AUTO_TRANS_ACCESS { get; set; }
        public Nullable<System.DateTime> TRANS_EXPIRY_DATE_ACCESS { get; set; }
        public Nullable<int> TRANS_TMS_ACCESS { get; set; }
        public string MEMO_ACCESS { get; set; }
        public Nullable<int> ALREADY_TRANS_TMS { get; set; }
        public Nullable<int> ALREADY_TRANS_TMS_AFT { get; set; }
        public string TRANS_Flag { get; set; }
    }
}
