//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_CA
    {
        public string ITEM_ID { get; set; }
        public string INVENTORY_STATUS { get; set; }
        public string CA_USE { get; set; }
        public string CA_DESC { get; set; }
        public string BANK { get; set; }
        public string CA_NUMBER { get; set; }
        public string MEMO { get; set; }
        public string APLY_DEPT { get; set; }
        public string APLY_SECT { get; set; }
        public string APLY_UID { get; set; }
        public string CHARGE_DEPT { get; set; }
        public string CHARGE_SECT { get; set; }
        public Nullable<System.DateTime> PUT_DATE { get; set; }
        public Nullable<System.DateTime> GET_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public string CA_USE_AFT { get; set; }
        public string CA_DESC_AFT { get; set; }
        public string BANK_AFT { get; set; }
        public string CA_NUMBER_AFT { get; set; }
        public string MEMO_AFT { get; set; }
        public string CHARGE_DEPT_AFT { get; set; }
        public string CHARGE_SECT_AFT { get; set; }
        public string CA_USE_ACCESS { get; set; }
        public string CA_DESC_ACCESS { get; set; }
        public string BANK_ACCESS { get; set; }
        public string CA_NUMBER_ACCESS { get; set; }
        public string MEMO_ACCESS { get; set; }
    }
}
