//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_REAL_ESTATE
    {
        public string ITEM_ID { get; set; }
        public string INVENTORY_STATUS { get; set; }
        public int GROUP_NO { get; set; }
        public string ESTATE_FORM_NO { get; set; }
        public Nullable<System.DateTime> ESTATE_DATE { get; set; }
        public string OWNERSHIP_CERT_NO { get; set; }
        public string LAND_BUILDING_NO { get; set; }
        public string HOUSE_NO { get; set; }
        public string ESTATE_SEQ { get; set; }
        public string MEMO { get; set; }
        public string APLY_DEPT { get; set; }
        public string APLY_SECT { get; set; }
        public string APLY_UID { get; set; }
        public string CHARGE_DEPT { get; set; }
        public string CHARGE_SECT { get; set; }
        public Nullable<System.DateTime> PUT_DATE { get; set; }
        public Nullable<System.DateTime> GET_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public string ESTATE_FORM_NO_AFT { get; set; }
        public Nullable<System.DateTime> ESTATE_DATE_AFT { get; set; }
        public string OWNERSHIP_CERT_NO_AFT { get; set; }
        public string LAND_BUILDING_NO_AFT { get; set; }
        public string HOUSE_NO_AFT { get; set; }
        public string ESTATE_SEQ_AFT { get; set; }
        public string MEMO_AFT { get; set; }
        public string CHARGE_DEPT_AFT { get; set; }
        public string CHARGE_SECT_AFT { get; set; }
        public string ESTATE_FORM_NO_ACCESS { get; set; }
        public Nullable<System.DateTime> ESTATE_DATE_ACCESS { get; set; }
        public string OWNERSHIP_CERT_NO_ACCESS { get; set; }
        public string LAND_BUILDING_NO_ACCESS { get; set; }
        public string HOUSE_NO_ACCESS { get; set; }
        public string ESTATE_SEQ_ACCESS { get; set; }
        public string MEMO_ACCESS { get; set; }
    }
}
