//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIA_LOG_MAIN
    {
        public long TRACKING_SEQ { get; set; }
        public string ACCESS_ACCOUNT { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string FROM_IP { get; set; }
        public System.DateTime ACCESS_DATE { get; set; }
        public System.TimeSpan ACCESS_TIME { get; set; }
        public string PROGFUN_NAME { get; set; }
        public string ACCESSOBJ_NAME { get; set; }
        public string EXECUTION_CONTENT { get; set; }
        public Nullable<int> AFFECT_ROWS { get; set; }
        public string PIA_OWNER1 { get; set; }
        public string PIA_OWNER2 { get; set; }
        public string PIA_TYPE { get; set; }
    
        public virtual PIA_EXEC_TYPE PIA_EXEC_TYPE { get; set; }
        public virtual PIA_TRACK_TYPE PIA_TRACK_TYPE { get; set; }
    }
}
