//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREA_EQUIP_HIS
    {
        public int HIS_ID { get; set; }
        public string APLY_NO { get; set; }
        public string TREA_EQUIP_ID { get; set; }
        public string EXEC_ACTION { get; set; }
        public string EQUIP_NAME { get; set; }
        public string CONTROL_MODE { get; set; }
        public Nullable<int> NORMAL_CNT { get; set; }
        public Nullable<int> RESERVE_CNT { get; set; }
        public string MEMO { get; set; }
        public string CONTROL_MODE_B { get; set; }
        public Nullable<int> NORMAL_CNT_B { get; set; }
        public Nullable<int> RESERVE_CNT_B { get; set; }
        public string MEMO_B { get; set; }
        public string APPR_STATUS { get; set; }
        public Nullable<System.DateTime> APPR_DATE { get; set; }
        public System.DateTime APLY_DATE { get; set; }
        public string APLY_UID { get; set; }
        public string APPR_UID { get; set; }
        public string APPR_DESC { get; set; }
        public string IS_DISABLED { get; set; }
        public string IS_DISABLED_B { get; set; }
        public string EQUIP_NAME_B { get; set; }
    }
}
