//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treasury.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREA_OPEN_REC
    {
        public string TREA_REGISTER_ID { get; set; }
        public string OPEN_TREA_TYPE { get; set; }
        public string OPEN_TREA_REASON { get; set; }
        public string OPEN_TREA_TIME { get; set; }
        public string EXEC_TIME_B { get; set; }
        public string EXEC_TIME_E { get; set; }
        public Nullable<System.DateTime> ACTUAL_PUT_TIME { get; set; }
        public Nullable<System.DateTime> ACTUAL_GET_TIME { get; set; }
        public string MEMO { get; set; }
        public string APPR_STATUS { get; set; }
        public string APPR_UID { get; set; }
        public Nullable<System.DateTime> APPR_DT { get; set; }
        public string APPR_DESC { get; set; }
        public string REGI_STATUS { get; set; }
        public string REGI_APPR_UID { get; set; }
        public Nullable<System.DateTime> REGI_APPR_DT { get; set; }
        public string REGI_APPR_DESC { get; set; }
        public string CREATE_UID { get; set; }
        public Nullable<System.DateTime> CREATE_DT { get; set; }
        public string LAST_UPDATE_UID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DT { get; set; }
        public System.DateTime OPEN_TREA_DATE { get; set; }
        public string CREATE_UNIT { get; set; }
        public string OPEN_TYPE { get; set; }
    }
}
