//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFGLEntities : DbContext
    {
        public dbFGLEntities()
            : base("name=dbFGLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CODE_USER> CODE_USER { get; set; }
        public virtual DbSet<PIA_LOG_MAIN> PIA_LOG_MAIN { get; set; }
        public virtual DbSet<SYS_CODE> SYS_CODE { get; set; }
        public virtual DbSet<SYS_SEQ> SYS_SEQ { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<CODE_SYS_INFO> CODE_SYS_INFO { get; set; }
        public virtual DbSet<FAP_SCHEDULE_JOB> FAP_SCHEDULE_JOB { get; set; }
        public virtual DbSet<FAP_PPAA_D_HIS> FAP_PPAA_D_HIS { get; set; }
        public virtual DbSet<FAP_VE_CODE> FAP_VE_CODE { get; set; }
        public virtual DbSet<FAP_VE_CODE_HIS> FAP_VE_CODE_HIS { get; set; }
        public virtual DbSet<FAP_APLY_REC> FAP_APLY_REC { get; set; }
        public virtual DbSet<SYS_PARA> SYS_PARA { get; set; }
        public virtual DbSet<FAP_VE_TRACE_HIS> FAP_VE_TRACE_HIS { get; set; }
        public virtual DbSet<FRT_MAIL_NOTIFY> FRT_MAIL_NOTIFY { get; set; }
        public virtual DbSet<FAP_CROSS_DEPARMENT> FAP_CROSS_DEPARMENT { get; set; }
        public virtual DbSet<FAP_CROSS_DEPARMENT_HIS> FAP_CROSS_DEPARMENT_HIS { get; set; }
        public virtual DbSet<FAP_NOTES_PAYABLE_RECEIVED> FAP_NOTES_PAYABLE_RECEIVED { get; set; }
        public virtual DbSet<FAP_NOTES_PAYABLE_RECEIVED_D> FAP_NOTES_PAYABLE_RECEIVED_D { get; set; }
        public virtual DbSet<FRT_MAIL_LOG> FRT_MAIL_LOG { get; set; }
        public virtual DbSet<FAP_CE_APPLY_HIS> FAP_CE_APPLY_HIS { get; set; }
        public virtual DbSet<FAP_CODE> FAP_CODE { get; set; }
        public virtual DbSet<FAP_CODE_HIS> FAP_CODE_HIS { get; set; }
        public virtual DbSet<FAP_FAPPYCD0_REPORT> FAP_FAPPYCD0_REPORT { get; set; }
        public virtual DbSet<FAP_MAIL_LABEL> FAP_MAIL_LABEL { get; set; }
        public virtual DbSet<FAP_MAIL_LABEL_D> FAP_MAIL_LABEL_D { get; set; }
        public virtual DbSet<FAP_PAID_DEPARMENT> FAP_PAID_DEPARMENT { get; set; }
        public virtual DbSet<FAP_PAID_DEPARMENT_HIS> FAP_PAID_DEPARMENT_HIS { get; set; }
        public virtual DbSet<FAP_VE_TRACE_PROC> FAP_VE_TRACE_PROC { get; set; }
        public virtual DbSet<FAP_VE_CLOSED_PROC> FAP_VE_CLOSED_PROC { get; set; }
        public virtual DbSet<FAP_VE_CLOSED_PROC_HIS> FAP_VE_CLOSED_PROC_HIS { get; set; }
        public virtual DbSet<FAP_VE_TRACE_PROC_HIS> FAP_VE_TRACE_PROC_HIS { get; set; }
        public virtual DbSet<SYS_PARA_HIS> SYS_PARA_HIS { get; set; }
        public virtual DbSet<FAP_TEL_CODE> FAP_TEL_CODE { get; set; }
        public virtual DbSet<FAP_TEL_CODE_HIS> FAP_TEL_CODE_HIS { get; set; }
        public virtual DbSet<FAP_TEL_POLI> FAP_TEL_POLI { get; set; }
        public virtual DbSet<FAP_TEL_PROC> FAP_TEL_PROC { get; set; }
        public virtual DbSet<FAP_TEL_CHECK> FAP_TEL_CHECK { get; set; }
        public virtual DbSet<FAP_TEL_CHECK_HIS> FAP_TEL_CHECK_HIS { get; set; }
        public virtual DbSet<FAP_HOUSEHOLD_ADDR> FAP_HOUSEHOLD_ADDR { get; set; }
        public virtual DbSet<FAP_TEL_INTERVIEW> FAP_TEL_INTERVIEW { get; set; }
        public virtual DbSet<FAP_TEL_INTERVIEW_HIS> FAP_TEL_INTERVIEW_HIS { get; set; }
        public virtual DbSet<FAP_PPAA_S_HIS> FAP_PPAA_S_HIS { get; set; }
        public virtual DbSet<FAP_VE_TRACE_POLI> FAP_VE_TRACE_POLI { get; set; }
        public virtual DbSet<FAP_VE_TRACE> FAP_VE_TRACE { get; set; }
        public virtual DbSet<FAP_TEL_SMS_TEMP> FAP_TEL_SMS_TEMP { get; set; }
        public virtual DbSet<FAP_VE_TRACE_IMP> FAP_VE_TRACE_IMP { get; set; }
        public virtual DbSet<CODE_FUNC> CODE_FUNC { get; set; }
        public virtual DbSet<CODE_ROLE> CODE_ROLE { get; set; }
        public virtual DbSet<CODE_ROLE_FUNC> CODE_ROLE_FUNC { get; set; }
        public virtual DbSet<CODE_USER_ROLE> CODE_USER_ROLE { get; set; }
    }
}
