//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DF_SCH_DEP
    {
        public int DEP_GUID { get; set; }
        public string SYS_TYPE { get; set; }
        public string PAR_DEP { get; set; }
        public string DEP_ID { get; set; }
        public string DEP_NAME { get; set; }
        public string DEP_LEVEL { get; set; }
        public string DEP_MEMO1 { get; set; }
        public string DEP_MEMO2 { get; set; }
        public string DEP_MEMO3 { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
