//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_TEL_INTERVIEW_HIS
    {
        public string aply_no { get; set; }
        public string tel_proc_no { get; set; }
        public string data_type { get; set; }
        public string tel_interview_id { get; set; }
        public Nullable<System.DateTime> tel_interview_datetime { get; set; }
        public string tel_result { get; set; }
        public Nullable<int> tel_result_cnt { get; set; }
        public string tel_appr_result { get; set; }
        public string called_person { get; set; }
        public string record_no { get; set; }
        public string tel_addr { get; set; }
        public string tel_zip_code { get; set; }
        public string tel_mail { get; set; }
        public string cust_tel { get; set; }
        public string level_1 { get; set; }
        public string level_2 { get; set; }
        public string cust_counter { get; set; }
        public Nullable<System.DateTime> counter_date { get; set; }
        public string reason { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> dispatch_date { get; set; }
        public string dispatch_status { get; set; }
        public string clean_status { get; set; }
        public Nullable<System.DateTime> clean_date { get; set; }
        public Nullable<System.DateTime> clean_f_date { get; set; }
        public string exec_action { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string appr_stat { get; set; }
        public string appr_id { get; set; }
        public Nullable<System.DateTime> approve_datetime { get; set; }
        public Nullable<System.DateTime> tel_interview_f_datetime { get; set; }
    }
}
