//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_TEL_CODE_HIS
    {
        public string aply_no { get; set; }
        public string code_type { get; set; }
        public string code_id { get; set; }
        public string proc_id { get; set; }
        public Nullable<int> std_1 { get; set; }
        public Nullable<int> std_2 { get; set; }
        public Nullable<int> std_3 { get; set; }
        public string fsc_range { get; set; }
        public string amt_range { get; set; }
        public string remark { get; set; }
        public string exec_action { get; set; }
        public string appr_stat { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string appr_id { get; set; }
        public Nullable<System.DateTime> approve_datetime { get; set; }
    }
}
