//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_MAIL_LABEL
    {
        public string id { get; set; }
        public string label_no { get; set; }
        public string send_style { get; set; }
        public string zip_code { get; set; }
        public string addr { get; set; }
        public string rcv_id { get; set; }
        public string memo { get; set; }
        public Nullable<int> number { get; set; }
        public string apply_name { get; set; }
        public string apply_id { get; set; }
        public string bulk_no { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_id { get; set; }
        public string rece_id { get; set; }
    }
}
