//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_TEL_SMS_TEMP
    {
        public string tel_std_aply_no { get; set; }
        public string check_no { get; set; }
        public string check_acct_short { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public Nullable<decimal> check_amt { get; set; }
        public string o_paid_cd { get; set; }
        public string paid_id { get; set; }
        public string paid_name { get; set; }
        public string system { get; set; }
        public string policy_no { get; set; }
        public int policy_seq { get; set; }
        public string id_dup { get; set; }
        public string appl_id { get; set; }
        public string appl_name { get; set; }
        public string ins_id { get; set; }
        public string ins_name { get; set; }
        public string sec_stat { get; set; }
        public string mobile { get; set; }
    }
}
