//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_PPAA_S_HIS
    {
        public string aply_no { get; set; }
        public string exec_action { get; set; }
        public string system { get; set; }
        public string source_op { get; set; }
        public string paid_id { get; set; }
        public Nullable<decimal> check_amt { get; set; }
        public string status { get; set; }
        public string check_no { get; set; }
        public string check_acct_short { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string area { get; set; }
        public string srce_from { get; set; }
        public string source_kind { get; set; }
        public string pay_no { get; set; }
        public Nullable<int> pay_seq { get; set; }
        public string re_paid_no { get; set; }
        public Nullable<int> re_paid_seq { get; set; }
        public Nullable<System.DateTime> re_paid_date { get; set; }
        public string re_paid_type { get; set; }
        public string re_paid_id { get; set; }
        public string re_paid_check_no { get; set; }
        public string re_bank_code { get; set; }
        public string re_sub_bank { get; set; }
        public string re_bank_account { get; set; }
        public string rt_system { get; set; }
        public string rt_policy_no { get; set; }
        public Nullable<int> rt_policy_seq { get; set; }
        public string rt_id_dup { get; set; }
        public string filler_10 { get; set; }
        public string filler_14 { get; set; }
        public string paid_name { get; set; }
        public string o_paid_tp { get; set; }
        public string o_paid_cd { get; set; }
        public Nullable<System.DateTime> re_paid_date_n { get; set; }
    }
}
