//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_TEL_CHECK
    {
        public string system { get; set; }
        public string check_no { get; set; }
        public string check_acct_short { get; set; }
        public string tel_std_aply_no { get; set; }
        public string tel_std_type { get; set; }
        public string fsc_range { get; set; }
        public string amt_range { get; set; }
        public string data_flag { get; set; }
        public string tel_proc_no { get; set; }
        public string tel_interview_id { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> dispatch_date { get; set; }
        public string dispatch_status { get; set; }
        public Nullable<System.DateTime> sms_date { get; set; }
        public string sms_status { get; set; }
        public string sec_stat { get; set; }
        public string data_status { get; set; }
        public string update_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    }
}
