//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_FAPPYCD0_REPORT
    {
        public string apply_no { get; set; }
        public string report_no { get; set; }
        public Nullable<System.DateTime> report_datetime { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string flag { get; set; }
    }
}
