//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_TEL_PROC
    {
        public string tel_proc_no { get; set; }
        public int seq_no { get; set; }
        public string aply_no { get; set; }
        public string data_type { get; set; }
        public string proc_id { get; set; }
        public Nullable<System.DateTime> proc_datetime { get; set; }
        public Nullable<System.DateTime> expect_datetime { get; set; }
        public string proc_status { get; set; }
        public string reason { get; set; }
        public string appr_id { get; set; }
        public Nullable<System.DateTime> appr_datetime { get; set; }
        public string appr_status { get; set; }
        public string appr_stat { get; set; }
    }
}
