//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_TEL_POLI
    {
        public string system { get; set; }
        public string policy_no { get; set; }
        public int policy_seq { get; set; }
        public string id_dup { get; set; }
        public string cust_tel { get; set; }
        public string tel_type { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    }
}
