//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_VE_TRACE_HIS
    {
        public string aply_no { get; set; }
        public string system { get; set; }
        public string check_no { get; set; }
        public string check_acct_short { get; set; }
        public string paid_id { get; set; }
        public string fsc_range { get; set; }
        public string status { get; set; }
        public string level_1 { get; set; }
        public string level_2 { get; set; }
        public string closed_no { get; set; }
        public string srce_pgm { get; set; }
        public string closed_desc { get; set; }
    }
}
