//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EMPLY
    {
        public string EMP_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_NAME_E { get; set; }
        public string ID_NO { get; set; }
        public string SEX { get; set; }
        public string BIRTHDAY { get; set; }
        public string AETNA_DT { get; set; }
        public string QUIT_DT { get; set; }
        public string SECT { get; set; }
        public string DPT_CD { get; set; }
        public string HO_ADDR { get; set; }
        public string FUN_CD { get; set; }
        public string FUN_DESCR { get; set; }
        public string DPT_NAME { get; set; }
        public string USR_ID { get; set; }
        public string EMAIL { get; set; }
        public string ext { get; set; }
        public string DPT_HEAD { get; set; }
        public string SGN_MGR { get; set; }
        public string Voice_No1 { get; set; }
        public string Address { get; set; }
    }
}
